{% set name = "gperftools" %}
{% set version = "2.9.1" %}
{% set sha256 = "484a88279d2fa5753d7e9dea5f86954b64975f20e796a6ffaf2f3426a674a06a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{name}}/{{name}}/archive/{{name}}-{{version}}.tar.gz
  sha256: {{ sha256 }}
  # locking up the s390x prefect build node
  skip: true  # [s390x]

build:
  number: 0
  skip: true  # [win]
  missing_dso_whitelist:         # [linux]
    - "*/libpthread.so.*"        # [linux]
    - "*/libm.so.*"              # [linux]
    - "*/libc.so.*"              # [linux]
    - "*/ld-linux-x86-64.so.*"   # [linux and x86_64]
    - "*/ld-linux-aarch64.so.*"  # [linux and aarch64]

requirements:
  host:
    - autoconf
    - automake
    - make
    - libtool
    #- {{ pin_compatible('libunwind', max_pin='x.x') }}  # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libunwind  # [linux]
  run:
    - perl

test:
  requires:
    - {{ compiler('c') }}
  commands:
    - pprof --help

about:
  home: http://github.com/gperftools/gperftools
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: 'The fastest malloc we have seen; works particularly well with threads and STL'
  description: |
    gperftools is a collection of a high-performance multi-threaded
    malloc() implementation, plus some pretty nifty performance analysis
    tools.
  doc_url: https://github.com/gperftools/gperftools/wiki
  dev_url: https://github.com/gperftools/gperftools

extra:
  recipe-maintainers:
    - xmnlab
