travis:
  secure:
    BINSTAR_TOKEN: NXjtS5aY/j5j2o1HolfhBN82zsITFdOxnqZsQSNgUViKD/u/WjZmFkDOZ8mEmDGBcRFaTWFTpHA3lHPSh1G10Z6AQM+wrbMQVk5WxGgBKYjPgZ41ZkYqC6wN8sc6sHEAMyMheBKYkf0CoG8TBfal2khahz//qXSTCmRHPfMlt/HB9XVOr/Y89bSI1SPcsnwVOrh43FHnt2GlY/Fz12e1rgxBdjmIC3QXU72wFkut4/5EX8ss6vUvpUGyX4MoMOXHrx+Tb7lQVkW+XAU+eGfjJ2ZxwElSgI1qtlBgXEu28M/IGzcB3hw5ZSAJwXkzfmgsQkTxzwXYTzFILsFnojUL1YZUzJIOO0kRrTOs8/oce8t1gYjy4wOnHNrzGE9OVAabA2q242XSGq6CFMO/hlS7FTujm9QLYnNXAu0WgaAT9gEuBvR/ukX52jpe3vyNQWsANfnrbcBcpXT4wXsQDOvzfriALvkbsQ9LUi+ZlsP8FnGomxiA/fRjRnQ4IgN5vbW9Bdw40x7m3mLYqv2OduidudqNcUrjeOyOZnlD7U0BDAKha+g23E7joWk2HnpwPpy5SsBVyLhx42ZSuaYbUvJbWRXX1IBA676Hl78l2tjyOuOsjSEhW9mrdB0btcB5thsB40KCdO0+ZZ/PLijD966WR35R4MJs9y948TMGAPMprJY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
